# .streamlit/config.toml

# --- Configuration du Thème Streamlit (Interface UI) ---
[theme]
# Couleur primaire (utilisée pour les boutons, liens, icônes)
primaryColor = "#004fa3" # Bleu RATP

# Couleur de fond de la page (blanc cassé pour un look classique)
backgroundColor = "#f5f5f5"

# Couleur de fond des éléments de contenu (zones de texte, sidebar, etc.)
secondaryBackgroundColor = "#ffffff"

# Couleur du texte
textColor = "#333333"

# Couleur des polices (par défaut)
font = "sans serif"


# --- Variables de Couleurs pour Plotly (Palette des Réseaux) ---
# Ces couleurs seront lues par app.py pour les graphiques.
[colors]
metro = "#4bc0ad"      # Vert/Turquoise RATP (Couleur dominante)
rer = "#e10b1a"        # Rouge RER
tramway = "#6fa832"    # Vert Tramway
val = "#3a87ad"        # Bleu secondaire
unknown = "#95a5a6"    # Gris
other = "#6c7a89"